=== Dan-0n/LMSGI_AE2/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="documentos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="libros">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="libro">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="título_libro" />
                          <xs:element name="capítulos">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="capítulo">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="título_capítulo" />
                                      <xs:element name="contenido_capítulo">
                                        <xs:complexType>
                                          <xs:attribute name="enlace" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="número_páginas" type="xs:integer" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="índice_libro" />
                          <xs:element name="sinopsis" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="tipo_clase" type="xs:string" use="required">
                        <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="novela"></xs:enumeration>
                            <xs:enumeration value="infantil"></xs:enumeration>
                            <xs:enumeration value="didactico"></xs:enumeration>
                            </xs:restriction>
                         </xs:simpleType>
                         </xs:attribute> 
                        <xs:attribute name="número_páginas" type="xs:integer" use="required" />
                      </xs:complexType>
                    </xs:element>
              <xs:element name="revistas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="revista">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="título_revista" />
                          <xs:element name="número" />
                          <xs:element name="índice_revista" />
                          <xs:element name="secciones_revista">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="sección_revista">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="contenido_revista">
                                        <xs:complexType>
                                          <xs:attribute name="enlace" type="xs:string" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="número_páginas" type="xs:integer" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="tipo_clase" type="xs:string" use="required">
                        <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="informática"></xs:enumeration>
                            <xs:enumeration value="corazón"></xs:enumeration>
                            <xs:enumeration value="coches"></xs:enumeration>
                            <xs:enumeration value="investigación"></xs:enumeration>
                            <xs:enumeration value="otras"></xs:enumeration>
                            </xs:restriction>
                         </xs:simpleType>
                         </xs:attribute> 
                        <xs:attribute name="número_páginas" type="xs:integer" use="required" />
                      </xs:complexType>
                    </xs:element>
              <xs:element name="periódicos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="periódico">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="secciones_periódico">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="sección_periódico">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="artículo">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="contenido_artículo">
                                              <xs:complexType>
                                                <xs:attribute name="información" type="xs:string" use="required" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute name="autor" type="xs:string" use="required" />
                                          <xs:attribute name="num" type="xs:integer" use="required" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tipo_sección" type="xs:string" use="required">
                                      <xs:simpleType>
                                       <xs:restriction base="xs:string">
                                         <xs:enumeration value="económica"></xs:enumeration>
                                         <xs:enumeration value="opinión"></xs:enumeration>
                                         <xs:enumeration value="deportes"></xs:enumeration>
                                         <xs:enumeration value="nacional"></xs:enumeration>
                                         <xs:enumeration value="internacional"></xs:enumeration>
                                        </xs:restriction>
                                      </xs:simpleType>
                                    </xs:attribute> 
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="índice_periódico" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="tipo_clase" type="xs:string" use="required">
                         <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="nacional"></xs:enumeration>
                            <xs:enumeration value="internacional"></xs:enumeration>
                            </xs:restriction>
                         </xs:simpleType>
                         </xs:attribute> 
                        <xs:attribute name="fecha_publicación" type="xs:date" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Dan-0n/LMSGI_AE2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca[
<!ELEMENT biblioteca (documentos+)>
<!ELEMENT documentos (libros,revistas,periódicos)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (título_libro,capítulos,índice_libro,sinopsis)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela|infantil|didáctico) #REQUIRED>
<!ATTLIST libro número_páginas CDATA #REQUIRED>
<!ELEMENT título_libro (#PCDATA)>
<!ELEMENT capítulos (capítulo+)>
<!ELEMENT capítulo (título_capítulo,contenido_capítulo)>
<!ATTLIST capítulo número_páginas CDATA #REQUIRED>
<!ELEMENT título_capítulo (#PCDATA)>
<!ELEMENT contenido_capítulo (#PCDATA)>
<!ATTLIST contenido_capítulo enlace CDATA #REQUIRED>
<!ELEMENT índice_libro (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT revistas (revista+)>
<!ELEMENT revista (título_revista,número,índice_revista,secciones_revista)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informática|corazón|coches|investigación|otras) #REQUIRED>
<!ATTLIST revista número_páginas CDATA #REQUIRED>
<!ELEMENT título_revista (#PCDATA)>
<!ELEMENT número (#PCDATA)>
<!ELEMENT índice_revista (#PCDATA)>
<!ELEMENT secciones_revista (sección_revista+)>
<!ELEMENT sección_revista (contenido_revista)>
<!ATTLIST sección_revista número_páginas CDATA #REQUIRED>
<!ELEMENT contenido_revista (#PCDATA)>
<!ATTLIST contenido_revista enlace CDATA #REQUIRED>
<!ELEMENT periódicos (periódico+)>
<!ELEMENT periódico (secciones_periódico,índice_periódico)>
<!ATTLIST periódicos id ID #REQUIRED>
<!ATTLIST periódico tipo_clase (nacional|internacional) #REQUIRED>
<!ATTLIST periódico fecha_publicación CDATA #REQUIRED>
<!ELEMENT secciones_periódico (sección_periódico+)>
<!ELEMENT sección_periódico (artículo,contenido_periódico)>
<!ATTLIST sección_periódico tipo_sección (económica|opinión|deportes|nacional|internacional) #REQUIRED>
<!ELEMENT artículo (#PCDATA)>
<!ATTLIST artículo autor CDATA #REQUIRED>
<!ATTLIST artículo num CDATA #REQUIRED>
<!ELEMENT contenido_artículo (#PCDATA)>
<!ATTLIST contenido_artículo información CDATA #REQUIRED>
<!ELEMENT índice_periódico (#PCDATA)>
]>


<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation= "biblioteca.xsd">
  <documentos>
    <libros>
        <libro id="L0001" tipo_clase="novela" número_páginas="0">
           <título_libro></título_libro>
           <capítulos>
               <capítulo número_páginas="0">
                   <título_capítulo></título_capítulo>
                   <contenido_capítulo enlace=""></contenido_capítulo> 
                </capítulo>
            </capítulos>
           <índice_libro></índice_libro>
           <sinopsis></sinopsis>
        </libro>
        <libro id="L0002" tipo_clase="infantil" número_páginas="0">
            <título_libro></título_libro>
            <capítulos>
                <capítulo número_páginas="0">
                    <título_capítulo></título_capítulo>
                    <contenido_capítulo enlace=""></contenido_capítulo> 
                 </capítulo>
             </capítulos>
            <índice_libro></índice_libro>
            <sinopsis></sinopsis>
        </libro>
        <libro id="L0003" tipo_clase="didáctico" número_páginas="0">
            <título_libro></título_libro>
            <capítulos>
                <capítulo número_páginas="0">
                    <título_capítulo></título_capítulo>
                    <contenido_capítulo enlace=""></contenido_capítulo> 
                 </capítulo>
             </capítulos>
            <índice_libro></índice_libro>
            <sinopsis></sinopsis>
        </libro>
    </libros>
    <revistas>
        <revista id="R0001" tipo_clase="informática" número_páginas="0">
            <título_revista></título_revista>
            <número></número>
            <índice_revista></índice_revista>
            <secciones_revista>
                <sección_revista número_páginas="0">
                    <contenido_revista enlace=""></contenido_revista>
                </sección_revista>
            </secciones_revista>
        </revista> 
        <revista id="R0002" tipo_clase="corazón" número_páginas="0">
            <título_revista></título_revista>
            <número></número>
            <índice_revista></índice_revista>
            <secciones_revista>
                <sección_revista número_páginas="0">
                    <contenido_revista enlace=""></contenido_revista>
                </sección_revista>
            </secciones_revista>
        </revista>
        <revista id="R0003" tipo_clase="coches" número_páginas="0">
            <título_revista></título_revista>
            <número></número>
            <índice_revista></índice_revista>
            <secciones_revista>
                <sección_revista número_páginas="0">
                    <contenido_revista enlace=""></contenido_revista>
                </sección_revista>
            </secciones_revista>
        </revista>
        <revista id="R0004" tipo_clase="investigación" número_páginas="0">
            <título_revista></título_revista>
            <número></número>
            <índice_revista></índice_revista>
            <secciones_revista>
                <sección_revista número_páginas="0">
                    <contenido_revista enlace=""></contenido_revista>
                </sección_revista>
            </secciones_revista>
        </revista>
        <revista id="R0005" tipo_clase="otras" número_páginas="0">
            <título_revista></título_revista>
            <número></número>
            <índice_revista></índice_revista>
            <secciones_revista>
                <sección_revista número_páginas="0">
                    <contenido_revista enlace=""></contenido_revista>
                </sección_revista>
            </secciones_revista>
        </revista>
    </revistas>
    <periódicos>
        <periódico id="P0001" tipo_clase="nacionales" fecha_publicación="1111-01-01">
            <secciones_periódico>
                <sección_periódico tipo_sección="económica">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="opinión">
                   <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="deportes">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="nacional">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="internacional">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                 </sección_periódico>
            </secciones_periódico>
            <índice_periódico></índice_periódico>
        </periódico>
        <periódico id="P0002" tipo_clase="internacionales" fecha_publicación="1111-01-01">
            <secciones_periódico>
                <sección_periódico tipo_sección="económica">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="opinión">
                   <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="deportes">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                </sección_periódico>
                <sección_periódico tipo_sección="nacional">
                    <artículo autor="" num="1">
                      <contenido_artículo información=""></contenido_artículo>
                    </artículo>
                    <artículo autor="" num="2">
